import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { dark } from "@clerk/themes";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full antialiased">
      <ClerkProvider
        appearance={{
          baseTheme: dark,
        }}
        localization={{
          locale: "en-US",
        }}
      >
        <body className="min-h-full bg-[#08090d] text-white antialiased">
          {children}
        </body>
      </ClerkProvider>
    </html>
  );
}
